USE northwind;

SELECT SUPPLIERID, COUNT(*)
FROM SUPPLIERS
GROUP BY SUPPLIERID;

SELECT SUM(SALARY)
FROM EMPLOYEES;

SELECT  PRODUCTNAME
		, UNITPRICE AS PRICE
FROM Products
ORDER BY UNITPRICE ASC;

SELECT  PRODUCTNAME
		, UNITPRICE AS PRICE
FROM Products
ORDER BY PRICE DESC;

-- CLASS DISCUSSION
-- SELECT PRODUCTNAME
-- 	, UNITPRICE AS PRICE
-- FROM PRODUCTS
-- WHERE UNITPRICE = (SELECT AVG(UNITPRICE));

